// +build !ignore_autogenerated

// Code generated by operator-sdk. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Broker) DeepCopyInto(out *Broker) {
	*out = *in
	in.Resources.DeepCopyInto(&out.Resources)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Broker.
func (in *Broker) DeepCopy() *Broker {
	if in == nil {
		return nil
	}
	out := new(Broker)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NameSrv) DeepCopyInto(out *NameSrv) {
	*out = *in
	in.Resources.DeepCopyInto(&out.Resources)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NameSrv.
func (in *NameSrv) DeepCopy() *NameSrv {
	if in == nil {
		return nil
	}
	out := new(NameSrv)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RocketMQ) DeepCopyInto(out *RocketMQ) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RocketMQ.
func (in *RocketMQ) DeepCopy() *RocketMQ {
	if in == nil {
		return nil
	}
	out := new(RocketMQ)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RocketMQ) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RocketMQList) DeepCopyInto(out *RocketMQList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]RocketMQ, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RocketMQList.
func (in *RocketMQList) DeepCopy() *RocketMQList {
	if in == nil {
		return nil
	}
	out := new(RocketMQList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RocketMQList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RocketMQSpec) DeepCopyInto(out *RocketMQSpec) {
	*out = *in
	in.NameSrv.DeepCopyInto(&out.NameSrv)
	in.MasterSlave.DeepCopyInto(&out.MasterSlave)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RocketMQSpec.
func (in *RocketMQSpec) DeepCopy() *RocketMQSpec {
	if in == nil {
		return nil
	}
	out := new(RocketMQSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RocketMQStatus) DeepCopyInto(out *RocketMQStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RocketMQStatus.
func (in *RocketMQStatus) DeepCopy() *RocketMQStatus {
	if in == nil {
		return nil
	}
	out := new(RocketMQStatus)
	in.DeepCopyInto(out)
	return out
}
